services:
  api_gateway:
    build: ./api-gateway
    ports: 
      - "8080:8080"
    volumes: 
      - ./api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment: 
      - PORT=8080

  users_service:
    build: ./users-service
    volumes:
      - ./users-service/src:/usr/src/app/src
    command: npm run start:dev

  notifications_service:
    build: ./notifications-service
    volumes:
      - ./notifications-service/src:/usr/src/app/src
    command: npm run start:dev

  relations_service:
    build: ./relations-service
    volumes:
      - ./relations-service/src:/usr/src/app/src
    command: npm run start:dev

  schema_service:
    build: ./schema-service
    volumes:
      - ./schema-service/src:/usr/src/app/src
    command: /bin/sh -c "npx prisma migrate dev && npm run start:dev"
    environment:
      - DATABASE_URL=postgresql://postgres:firendsDB@postgres:5432/firendsDB

  status_service:
    build: ./status-service
    volumes:
      - ./status-service/src:/usr/src/app/src
    command: npm run start:dev

  nats:
    image: nats
    ports:
      - 4222:4222

  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=firendsDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=strongpassword
    ports:
      - "5432:5432"

volumes:
  postgres-data:
